### ISSUE TITLE
Gemeinden

### ISSUE THREAD

**Issue by tyrasd** [abaumg/covid19-bz-scraper#1]
I would find it interesting to have this data also per municipality. Maybe similar to how the [protezione civile](https://github.com/pcm-dpc/COVID-19) publishes the data per [province](https://github.com/pcm-dpc/COVID-19/blob/master/dati-province/dpc-covid19-ita-province.csv).

This data would be available through the daily press releases, e.g.:

* http://www.provinz.bz.it/news/de/news.asp?news_action=300&news_image_id=1062450 from http://www.provinz.bz.it/news/de/news.asp?news_action=4&news_article_id=637083

@jalaska already has some python code for converting the shreadsheet to more machine-readable data format, which could potentially be used for this.

Unfortunately, these spreadsheets seem to be accessible only through these daily press releases, and not through sites like http://www.provinz.bz.it/sicherheit-zivilschutz/zivilschutz/coronavirus.asp. This would make the automatic scraping a bit cumbersome :thinking: . But maybe there's a secondary source for this, which I don't know?

**Comment by tyrasd** [comment]
see https://github.com/tyrasd/covid19-bz-scraper/blob/master/data/covid19_bz_municipalities.csv for code and data from 2020-03-18 to today. There would also be data available from 2020-03-13, but the format of the early spreadsheet is slightly differnt, so I can't pull it in automatically. Maybe that could be done manually, perhaps?

**Comment by abaumg** [comment]
Very interesting! I was thinking about scraping the daily press releases anyway, because the press releases include some other interesting data (e.g. number of tests, number of ICU patients etc.)

**Comment by abaumg** [comment]
> Unfortunately, these spreadsheets seem to be accessible only through these daily press releases, and not through sites like http://www.provinz.bz.it/sicherheit-zivilschutz/zivilschutz/coronavirus.asp. This would make the automatic scraping a bit cumbersome thinking . But maybe there's a secondary source for this, which I don't know?

I looks like on http://www.provinz.bz.it/sicherheit-zivilschutz/zivilschutz/aktuelle-daten-zum-coronavirus.asp they have added a static link to the XLS: https://afbs.provinz.bz.it/upload/coronavirus/CoronavirusPositivi.xlsx and https://afbs.provinz.bz.it/upload/coronavirus/CoronavirusQuarantaene.xlsx
