### ISSUE TITLE
deceased_total

### ISSUE THREAD

**Issue by tyrasd** [abaumg/covid19-bz-scraper#4]
If I read http://www.provinz.bz.it/news/de/news.asp?news_action=4&news_article_id=637196 correctly, the column `deceased_total` from the new _detailed_ data files area not actually the total number of deceased persons, but the number of people deceased in a hospital. Some persons might be counted in this value _and_ the value of `deceased_senior_residents`.

Probably better rename column `deceased_total` to `deceased_in_hospital` (or similar)?

**Comment by tyrasd** [comment]
see also today's press release: http://www.provinz.bz.it/news/de/news.asp?news_action=4&news_article_id=637203:

> In den Krankenhäusern des Sanitätsbetriebes Verstorbene: 81
> In den Seniorenwohnheimen Verstorbene: 39
> Mit Covid-19 Verstorbene gesamt: 120
> […]
> verstorbene Heimbewohner: 43 (4 davon im Krankenhaus verstorben)

**Comment by abaumg** [comment]
Today, the `"Verstorbene gesamt"` line was missing entirely: http://www.provinz.bz.it/news/de/news.asp?news_action=4&news_article_id=637263

I'm not sure how to handle this mess.

**Comment by abaumg** [comment]
After [some chaos](https://www.rainews.it/tgr/tagesschau/articoli/2020/04/tag-coronatote-statistik-suedtirol-fauxpas-florian-zerzer-d5acd3d9-bb24-4d8d-a99e-0c710a33a4e1.html), the data is clean:
e.g. [http://www.provinz.bz.it/news/de/news.asp?news_action=4&news_article_id=638778](http://www.provinz.bz.it/news/de/news.asp?news_action=4&news_article_id=638778)
> In den Krankenhäusern des Sanitätsbetriebes Verstorbene: 173 (+0)
> In den Seniorenwohnheimen Verstorbene: 117 (+0)
> Gesamtzahl der mit Covid-19 Verstorbenen: 290
