### ISSUE TITLE
Municipality Data not getting updated anymore?

### ISSUE THREAD

**Issue by MinerMax555** [abaumg/covid19-bz-scraper#9]
Hi,

First of all thank you a lot for this repo, really saved a lot of work to process the data for municipalities for me.

Though a question, I noticed that the municipality data hasn't been updated for this week. Same seems to have happened to the detailed province data for the last 2 months. 
Is this intentional or did some automated job die without you noticing? From what I can tell the data source (https://afbs.provinz.bz.it/upload/coronavirus/CoronavirusPositivi.xlsx) is still getting daily updates. If so, do you plan to fix/update it or should I instead just set up my own import?

Best regards,
Max

**Comment by tyrasd** [comment]
they changed the spreadsheet columns :facepalm: 

![image](https://user-images.githubusercontent.com/1927298/96991670-154ad400-1529-11eb-8732-c8062681200c.png)

so the scripts needs to be adjusted slightly
